name: .NET Framework

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Restore NuGet Packages
      run: nuget restore YAD.sln
      
    - name: Build
      run: msbuild.exe YAD.sln /p:platform="Any CPU" /p:Configuration="Release"
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: YADFiles
        path: YAD\bin\Release
      
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: YADFiles
          path: YADFiles

      - name: Zip FolderX
        run: |
          zip -r YAD.zip YADFiles
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          body: Automated release from GitHub Actions
          files: YAD.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
